namespace GameHub.Application.DTOs.HeroBanner;

public record HeroBannerDto(
    string Id, string Title, string? Subtitle, string? Description,
    string? Badge, double? DiscountPercentage,
    string? PrimaryButtonText, string? PrimaryButtonUrl,
    string? SecondaryButtonText, string? SecondaryButtonUrl,
    string? GameId, string? GameName, string? GameSlug,
    string? CategoryName, string? PlatformName,
    double OverlayOpacity, string OverlayColor,
    string TextColor, string? FontFamily, string? FontSize, string? FontWeight,
    string ButtonStyle, string ButtonColor, string ButtonHoverColor,
    string HorizontalAlignment, string VerticalAlignment,
    string BackgroundType, string? ImageUrl, string? VideoUrl,
    string? YoutubeUrl, string? Mp4Url, string? WebMUrl,
    string SolidColor, string? GradientStart, string? GradientEnd, string? GradientDirection,
    bool AnimatedBackground, string? LottieUrl, bool ThreeJsEnabled,
    bool ParticleEnabled, string? ParticleType, string? BackgroundLayers,
    bool FloatingObjects, bool FloatingControllers, bool FloatingCds, bool FloatingCubes,
    string TextAnimation,
    bool AutoplayEnabled, bool InfiniteLoopEnabled, int CarouselTransitionSpeed,
    string CarouselAnimationType, bool PauseOnHover,
    int SortOrder, int Priority, bool IsPublished, bool IsFeatured, bool IsArchived,
    DateTime? PublishStartDate, DateTime? PublishEndDate,
    string? PrimaryColor, string? SecondaryColor, string? AccentColor, string? BgColor,
    string? HeroHeight, string? HeroWidth, string? CssBorderRadius, string? CssShadow,
    string? CssSpacing, string? CssPadding, string? CssMargins,
    int AnimationDuration, int TransitionSpeed,
    string? DesktopSettings, string? TabletSettings, string? MobileSettings,
    DateTime CreatedAt, DateTime? UpdatedAt
);

public record CreateHeroBannerRequest(
    string Title, string? Subtitle, string? Description,
    string? Badge, double? DiscountPercentage,
    string? PrimaryButtonText, string? PrimaryButtonUrl,
    string? SecondaryButtonText, string? SecondaryButtonUrl,
    string? GameId, string? GameName, string? CategoryName, string? PlatformName,
    double OverlayOpacity, string OverlayColor,
    string TextColor, string? FontFamily, string? FontSize, string? FontWeight,
    string ButtonStyle, string ButtonColor, string ButtonHoverColor,
    string HorizontalAlignment, string VerticalAlignment,
    string BackgroundType, string? ImageUrl, string? VideoUrl,
    string? YoutubeUrl, string? Mp4Url, string? WebMUrl,
    string SolidColor, string? GradientStart, string? GradientEnd, string? GradientDirection,
    bool AnimatedBackground, string? LottieUrl, bool ThreeJsEnabled,
    bool ParticleEnabled, string? ParticleType, string? BackgroundLayers,
    bool FloatingObjects, bool FloatingControllers, bool FloatingCds, bool FloatingCubes,
    string TextAnimation,
    bool AutoplayEnabled, bool InfiniteLoopEnabled, int CarouselTransitionSpeed,
    string CarouselAnimationType, bool PauseOnHover,
    int SortOrder, int Priority, bool IsPublished, bool IsFeatured, bool IsArchived,
    DateTime? PublishStartDate, DateTime? PublishEndDate,
    string? PrimaryColor, string? SecondaryColor, string? AccentColor, string? BgColor,
    string? HeroHeight, string? HeroWidth, string? CssBorderRadius, string? CssShadow,
    string? CssSpacing, string? CssPadding, string? CssMargins,
    int AnimationDuration, int TransitionSpeed,
    string? DesktopSettings, string? TabletSettings, string? MobileSettings
);

public record UpdateHeroBannerRequest(
    string? Title, string? Subtitle, string? Description,
    string? Badge, double? DiscountPercentage,
    string? PrimaryButtonText, string? PrimaryButtonUrl,
    string? SecondaryButtonText, string? SecondaryButtonUrl,
    string? GameId, string? GameName, string? CategoryName, string? PlatformName,
    double? OverlayOpacity, string? OverlayColor,
    string? TextColor, string? FontFamily, string? FontSize, string? FontWeight,
    string? ButtonStyle, string? ButtonColor, string? ButtonHoverColor,
    string? HorizontalAlignment, string? VerticalAlignment,
    string? BackgroundType, string? ImageUrl, string? VideoUrl,
    string? YoutubeUrl, string? Mp4Url, string? WebMUrl,
    string? SolidColor, string? GradientStart, string? GradientEnd, string? GradientDirection,
    bool? AnimatedBackground, string? LottieUrl, bool? ThreeJsEnabled,
    bool? ParticleEnabled, string? ParticleType, string? BackgroundLayers,
    bool? FloatingObjects, bool? FloatingControllers, bool? FloatingCds, bool? FloatingCubes,
    string? TextAnimation,
    bool? AutoplayEnabled, bool? InfiniteLoopEnabled, int? CarouselTransitionSpeed,
    string? CarouselAnimationType, bool? PauseOnHover,
    int? SortOrder, int? Priority, bool? IsPublished, bool? IsFeatured, bool? IsArchived,
    DateTime? PublishStartDate, DateTime? PublishEndDate,
    string? PrimaryColor, string? SecondaryColor, string? AccentColor, string? BgColor,
    string? HeroHeight, string? HeroWidth, string? CssBorderRadius, string? CssShadow,
    string? CssSpacing, string? CssPadding, string? CssMargins,
    int? AnimationDuration, int? TransitionSpeed,
    string? DesktopSettings, string? TabletSettings, string? MobileSettings
);

public record ReorderBannerRequest(string Id, int SortOrder);
